library:
  source-dirs: src
tests:
  tapl-test:
    source-dirs: test
    main: Spec.hs
    dependencies:
    - tapl
    - hspec
copyright: Yokoyama Haruki
category: Web
maintainer: automatonix@gmail.com
ghc-options:
- -Wall
- -threaded
- -rtsopts
- -with-rtsopts=-N
dependencies:
- parser-combinators
- megaparsec
- base >=4.7 && <5
- deepseq
- microlens
name: tapl
version: 0.1.0
author: maton
github: matonix/tapl
license: BSD3
executables:
  tapl:
    source-dirs: app
    main: Main.hs
    dependencies:
    - tapl
